### ISSUE TITLE
NEXT_PUBLIC_BOOK_INFO_API_URL, NEXT_PUBLIC_BOOK_API_KEY 키를 클라이언트에서 숨기기

### ISSUE THREAD

**Issue by hyukkwonepic** [princessbook/booktique#29]
## 설명

https://github.com/princessbook/booktique/blob/55e1f539f18da2ad31f5a1ca6a035c5416b38116/src/app/api/getBookInfo/%5Bid%5D/route.ts#L9-L10

NEXT_PUBLIC_BOOK_INFO_API_URL, NEXT_PUBLIC_BOOK_API_KEY키는 현재 api route에서만 사용하고 있습니다. 이 키는 특히 공개되면 누구나 사용할수 있기때문에 NEXT_PUBLIC prefix를 제거하여 클라이언트 사이드에서 가려야합니다.

### to-be

ALADIN_BOOK_INFO_API_URL, ALADIN_BOOK_API_KEY

- ALADIN 이라는 prefix를 붙여서 명시적으로 키를 표현합니다.

**Comment by cheolgyun7** [comment]
다른 파일에서도 꼭지킵시다

**Comment by brownrice0916** [comment]
감사합니다감사합니다

**Comment by HuaHuaChiChi** [comment]
제가 책임지고 수정해놓도록 하겠습니다

**Comment by rlaedous** [comment]
감사합니다!!
